//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras_Devoluciones
    {
        public Compras_Devoluciones()
        {
            this.Compras_Devoluciones_Detalles = new HashSet<Compras_Devoluciones_Detalles>();
        }
    
        public long PKCompraDevolucionID { get; set; }
        public System.DateTime FechaDevolucion { get; set; }
        public long FKCompraID { get; set; }
        public bool Estado { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual ICollection<Compras_Devoluciones_Detalles> Compras_Devoluciones_Detalles { get; set; }
    }
}
