//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public Compras()
        {
            this.Compras_Detalles = new HashSet<Compras_Detalles>();
            this.Compras_Devoluciones = new HashSet<Compras_Devoluciones>();
        }
    
        public long PKCompraID { get; set; }
        public System.DateTime Fecha { get; set; }
        public int FKEmpleadoID { get; set; }
        public int FKProveedorID { get; set; }
        public string Estatus { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Compras_Detalles> Compras_Detalles { get; set; }
        public virtual ICollection<Compras_Devoluciones> Compras_Devoluciones { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
