//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuentos
    {
        public Descuentos()
        {
            this.Ventas_Detalles = new HashSet<Ventas_Detalles>();
        }
    
        public int PKDescuentoID { get; set; }
        public string NombreDescuento { get; set; }
        public string CantidadDescuento { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Ventas_Detalles> Ventas_Detalles { get; set; }
    }
}
