//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inventario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FactEntities2 : DbContext
    {
        public FactEntities2()
            : base("name=FactEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Compras> Compras { get; set; }
        public DbSet<Compras_Detalles> Compras_Detalles { get; set; }
        public DbSet<Compras_Devoluciones> Compras_Devoluciones { get; set; }
        public DbSet<Compras_Devoluciones_Detalles> Compras_Devoluciones_Detalles { get; set; }
        public DbSet<Descuentos> Descuentos { get; set; }
        public DbSet<Empleados> Empleados { get; set; }
        public DbSet<Modulos> Modulos { get; set; }
        public DbSet<Productos> Productos { get; set; }
        public DbSet<Productos_Categorias> Productos_Categorias { get; set; }
        public DbSet<Productos_Presentaciones> Productos_Presentaciones { get; set; }
        public DbSet<Productos_Unidades> Productos_Unidades { get; set; }
        public DbSet<Proveedores> Proveedores { get; set; }
        public DbSet<Rangos> Rangos { get; set; }
        public DbSet<RangosModulos> RangosModulos { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Ventas> Ventas { get; set; }
        public DbSet<Ventas_Detalles> Ventas_Detalles { get; set; }
        public DbSet<Ventas_Devoluciones> Ventas_Devoluciones { get; set; }
        public DbSet<Ventas_Devoluciones_Detalles> Ventas_Devoluciones_Detalles { get; set; }
    }
}
