//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.Compras_Detalles = new HashSet<Compras_Detalles>();
            this.Compras_Devoluciones_Detalles = new HashSet<Compras_Devoluciones_Detalles>();
            this.Ventas_Detalles = new HashSet<Ventas_Detalles>();
            this.Ventas_Devoluciones_Detalles = new HashSet<Ventas_Devoluciones_Detalles>();
        }
    
        public long PKProductoID { get; set; }
        public string DescProducto { get; set; }
        public int Existencia { get; set; }
        public int ExistenciaMinima { get; set; }
        public int FKCategoria { get; set; }
        public Nullable<decimal> PrecioUnidadVenta { get; set; }
        public Nullable<decimal> PrecioUnidadCompra { get; set; }
        public bool Estado { get; set; }
        public string ISV { get; set; }
    
        public virtual ICollection<Compras_Detalles> Compras_Detalles { get; set; }
        public virtual ICollection<Compras_Devoluciones_Detalles> Compras_Devoluciones_Detalles { get; set; }
        public virtual Productos_Categorias Productos_Categorias { get; set; }
        public virtual ICollection<Ventas_Detalles> Ventas_Detalles { get; set; }
        public virtual ICollection<Ventas_Devoluciones_Detalles> Ventas_Devoluciones_Detalles { get; set; }
    }
}
