//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_Categorias
    {
        public Productos_Categorias()
        {
            this.Productos = new HashSet<Productos>();
        }
    
        public int PKCategoriaID { get; set; }
        public string NombreCategoria { get; set; }
        public string DescripcionCategoria { get; set; }
    
        public virtual ICollection<Productos> Productos { get; set; }
    }
}
