//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas_Devoluciones
    {
        public Ventas_Devoluciones()
        {
            this.Ventas_Devoluciones_Detalles = new HashSet<Ventas_Devoluciones_Detalles>();
        }
    
        public long PKVentaDevolucionID { get; set; }
        public System.DateTime FechaDevolucion { get; set; }
        public long FKVentaID { get; set; }
        public bool Estado { get; set; }
    
        public virtual Ventas Ventas { get; set; }
        public virtual ICollection<Ventas_Devoluciones_Detalles> Ventas_Devoluciones_Detalles { get; set; }
    }
}
