//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public Ventas()
        {
            this.Ventas_Detalles = new HashSet<Ventas_Detalles>();
            this.Ventas_Devoluciones = new HashSet<Ventas_Devoluciones>();
        }
    
        public long PKVentaID { get; set; }
        public System.DateTime Fecha { get; set; }
        public int FKEmpleadoID { get; set; }
        public string Estatus { get; set; }
        public bool Estado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual ICollection<Ventas_Detalles> Ventas_Detalles { get; set; }
        public virtual ICollection<Ventas_Devoluciones> Ventas_Devoluciones { get; set; }
    }
}
